name: CI-CD Deploy to EC2 (Spring Boot)

on:
  push:
    branches: ["main"]
  workflow_dispatch: {}

concurrency:
  group: deploy-to-ec2
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Make gradlew executable
        run: chmod +x gradlew

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Find JAR
        id: find_jar
        run: |
          JAR=$(ls build/libs/*-SNAPSHOT.jar 2>/dev/null || ls build/libs/*.jar | head -n1)
          echo "jar=$JAR" >> $GITHUB_OUTPUT

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: ${{ steps.find_jar.outputs.jar }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Check required secrets
        run: |
          [ -n "${{ secrets.EC2_HOST }}" ] || (echo "❌ EC2_HOST empty"; exit 1)
          [ -n "${{ secrets.EC2_USER }}" ] || (echo "❌ EC2_USER empty"; exit 1)
          [ -n "${{ secrets.EC2_SSH_KEY }}" ] || (echo "❌ EC2_SSH_KEY empty"; exit 1)

      - uses: actions/download-artifact@v4
        with:
          name: app
          path: .

      - name: Prepare SSH key (raw PEM)
        shell: bash
        run: |
          # 시크릿(멀티라인) → 파일
          printf "%s" '${{ secrets.EC2_SSH_KEY }}' > key.pem
          # CRLF 제거(윈도 개행 방지)
          sed -i 's/\r$//' key.pem
          chmod 600 key.pem

          # 간단 검증: 헤더/푸터 체크
          head -n1 key.pem | grep -E 'BEGIN .* PRIVATE KEY' >/dev/null || { echo "❌ Invalid PEM header"; exit 1; }
          tail -n1 key.pem | grep -E 'END .* PRIVATE KEY' >/dev/null || { echo "❌ Invalid PEM footer"; exit 1; }

      # (선택) 인증 빠른 점검 — 실패하면 바로 원인 파악 용이
      - name: Quick SSH auth check
        run: |
          ssh -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -i key.pem \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'echo OK'

      - name: Upload JAR to EC2
        run: |
          scp -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -i key.pem ./*.jar \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/opt/dotcar/app.jar

      - name: Restart service
        run: |
          ssh -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -i key.pem \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
              sudo systemctl daemon-reload &&
              sudo systemctl restart dotcar &&
              sleep 3 &&
              sudo systemctl status dotcar --no-pager -l
            "