name: CI-CD Deploy to EC2 (Spring Boot)

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
      - name: Build with Gradle
        run: ./gradlew clean build -x test
      - name: Find JAR
        id: find_jar
        run: |
          JAR=$(ls build/libs/*-SNAPSHOT.jar 2>/dev/null || ls build/libs/*.jar | head -n1)
          echo "jar=$JAR" >> $GITHUB_OUTPUT
      - uses: actions/upload-artifact@v4
        with:
          name: app
          path: ${{ steps.find_jar.outputs.jar }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: app
          path: .
      - name: Prepare SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem
      - name: Upload JAR to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i key.pem ./*.jar \
              ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/opt/dotcar/app.jar
      - name: Restart service
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem \
              ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
                sudo systemctl daemon-reload &&
                sudo systemctl restart dotcar &&
                sleep 3 &&
                sudo systemctl status dotcar --no-pager -l
              "